trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  environmentName: 'dev'
  backendRG: 'skink-rg'
  backendSA: 'skinktfstate'
  backendKey: 'dev-terraform.tfstate'
  azureServiceConnection: 'intech'
  approvalEmail: 'lukebyrnee97@gmail.com'

stages:
  # Dev Stage
  - stage: Dev
    displayName: 'Dev Environment'
    jobs:
      - template: terraform-template.yml
        parameters:
          environmentName: $(environmentName)
          backendRG: $(backendRG)
          backendSA: $(backendSA)
          backendKey: $(backendKey)
          azureServiceConnection: $(azureServiceConnection)
          approvalEmail: $(approvalEmail)

  # Test Stage
  - stage: Test
    displayName: 'Test Environment'
    dependsOn: Dev
    jobs:
      - template: terraform-template.yml
        parameters:
          environmentName: $(environmentName)
          backendRG: $(backendRG)
          backendSA: $(backendSA)
          backendKey: $(backendKey)
          azureServiceConnection: $(azureServiceConnection)
          approvalEmail: $(approvalEmail)

  # Prod Stage
  - stage: Prod
    displayName: 'Prod Environment'
    dependsOn: Test
    jobs:
      - template: terraform-template.yml
        parameters:
          environmentName: $(environmentName)
          backendRG: $(backendRG)
          backendSA: $(backendSA)
          backendKey: $(backendKey)
          azureServiceConnection: $(azureServiceConnection)
          approvalEmail: $(approvalEmail)
